# modules/TaskManager.py

import json
from algorithm.CSP_joao import employee_scheduling
from algorithm.genetic_algorithm import solve as genetic_alg_solver
from algorithm.heuristic_sol_gabi import solve as hill_clibing_alg_solver
from algorithm.ILP import solve as ilp_solver
from algorithm.greedyRandomized import solve as greedy_randomized_solver
from algorithm.greedyClimbing import solve as greedy_climbing_solver
from algorithm.CSP import solve as csp_solver
from algorithm.CSP_Engine import solve as csp_engine_solver
from algorithm.greedyClimbingEngine import solve as grhc_engine_solver

class TaskManager:
    def __init__(self):
        # No futuro, você pode adicionar suporte a múltiplos algoritmos aqui
        # ToDo: this must be converted to a json file that can be dynamically modified
        self.algorithms = {
            "CSP Scheduling": employee_scheduling,
            "genetic_algorithm": genetic_alg_solver,
            "hill climbing": hill_clibing_alg_solver,
            "linear programming": ilp_solver,
            "Greedy Randomized": greedy_randomized_solver,
            "Greedy Randomized + Hill Climbing": greedy_climbing_solver,
            "CSP": csp_solver,
            "CSP_ENGINE": csp_engine_solver,
            "GRHC_ENGINE": grhc_engine_solver
        }

    def run_task(self, task_id, title, algorithm_name="CSP Scheduling", vacations=None, minimuns=None, employees=None, maxTime=10, year=None, shifts=2, rules=None):
        print(f"\n[DEBUG] Vacations received:\n{vacations}")
        print(f"[DEBUG] Minimuns received:\n{minimuns}")
        print(f"[DEBUG] Rules received:\n{json.dumps(rules, indent=2) if rules else 'None'}")

        if algorithm_name not in self.algorithms:
            raise ValueError(f"Algorithm '{algorithm_name}' not found.")

        print(f"[TaskManager] Executing algorithm '{algorithm_name}' with Task ID: {task_id}")
        algorithm = self.algorithms[algorithm_name]

        if not rules:
            from pathlib import Path
            current_dir = Path(__file__).parent
            rules_path = current_dir / "rules.json"
            with open(rules_path) as f:
                rules = json.load(f)
                
        if isinstance(rules, dict) and "rules" in rules:
            rules_json = rules
        else:
            rules_json = {"rules": rules}

        if algorithm_name in ["linear programming", "hill climbing", "Greedy Randomized", "Greedy Randomized + Hill Climbing", "CSP", "GRHC_ENGINE", "CSP_ENGINE",]:
            schedule_data = algorithm(vacations=vacations, minimuns=minimuns, employees=employees, maxTime=maxTime, year=year, shifts=shifts, rules=rules_json,
            )
        else:
            schedule_data = algorithm()

        print(f"[TaskManager] Algorithm '{algorithm_name}' successfully finalized.")
        print(f"[TaskManager] Schedule generated by '{algorithm_name}' algorithm: {schedule_data}")
        return schedule_data