# modules/TaskManager.py

import json
from algorithms.ILP import solve as ilp_solver
from algorithms.greedyRandomized import solve as greedy_randomized_solver
from algorithms.greedyClimbing import solve as greedy_climbing_solver
from algorithms.CSP import solve as csp_solver
from algorithms.CSPv2 import solve as cspv2_solver
from algorithms.ILP_H import solve as ILP_13Hours_solver
from algorithms.CSP_H import solve as CSP_13Hours_solver
from algorithms.CSP_Afonso_Hours import solve as CSP_Afonso_Hours_solver
from algorithms.ILP_Half_Hour import solve as ILP_13_Half_Intervals_solver
from algorithms.CSP_Extra import solve as CSP_Extra_Hours_solver
from algorithms.ILP_Extra import solve as ILP_Extra_Hours_solver

class TaskManager:
    def __init__(self):
        # No futuro, você pode adicionar suporte a múltiplos algoritmos aqui
        # ToDo: this must be converted to a json file that can be dynamically modified
        self.algorithms = {
            "linear programming": ilp_solver,
            "Greedy Randomized": greedy_randomized_solver,
            "Greedy Randomized + Hill Climbing": greedy_climbing_solver,
            "CSP": csp_solver,
            "CSPv2": cspv2_solver,
            "ILP_13Hours": ILP_13Hours_solver,
            "CSP_13Hours": CSP_13Hours_solver,
            "CSP_Afonso_Hours": CSP_Afonso_Hours_solver,
            "ILP_13_Half_Intervals": ILP_13_Half_Intervals_solver,
            "CSP_Extra_Hours": CSP_Extra_Hours_solver,
            "ILP_Extra_Hours": ILP_Extra_Hours_solver,
        }

    def run_task(self, task_id, title, algorithm_name="CSP Scheduling", vacations=None, minimuns=None, employees=None, maxTime=10, year=None, shifts=2, rules=None, hours=13):
        print(f"\n[DEBUG] Vacations received:\n{vacations}")
        print(f"[DEBUG] Minimuns received:\n{minimuns}")
        print(f"[DEBUG] Rules received:\n{json.dumps(rules, indent=2) if rules else 'None'}")

        if algorithm_name not in self.algorithms:
            raise ValueError(f"Algorithm '{algorithm_name}' not found.")

        print(f"[TaskManager] Executing algorithm '{algorithm_name}' with Task ID: {task_id}")
        algorithm = self.algorithms[algorithm_name]

        if not rules:
            from pathlib import Path
            current_dir = Path(__file__).parent
            rules_path = current_dir /  "rules.json"
            with open(rules_path) as f:
                rules = json.load(f)
                
        if isinstance(rules, dict) and "rules" in rules:
            rules_json = rules
        else:
            rules_json = {"rules": rules}

        if algorithm_name in ["linear programming", "hill climbing", "Greedy Randomized", "Greedy Randomized + Hill Climbing", "CSP", "GRHC_ENGINE", "CSP_ENGINE", "Greedy Randomized Engine", "ILP Engine", "linear programming 2", "CSPv2"]:

            schedule_data = algorithm(vacations=vacations, minimuns=minimuns, employees=employees, maxTime=maxTime, year=year, shifts=shifts, rules=rules_json)
        elif algorithm_name in ["ILP_13Hours", "CSP_13Hours", "CSP_Afonso_Hours", "ILP_13_Half_Intervals", "ILP_Half_Hour", "CSP_Extra_Hours", "ILP_Extra_Hours"]:
            schedule_data = algorithm(vacations=vacations, minimuns=minimuns, employees=employees, maxTime=maxTime, year=year, hours=hours, rules=rules_json)
        else:
            schedule_data = algorithm()

        print(f"[TaskManager] Algorithm '{algorithm_name}' successfully finalized.")
        print(f"[TaskManager] Schedule generated by '{algorithm_name}' algorithm: {schedule_data}")
        return schedule_data