import traceback
import pandas as pd
import re
import json
from datetime import date, datetime
import holidays

def load_minimums_from_csv(mins_csv_file):
    """
    Loads hourly minimums from CSV file with structure:
    Hora | 2021-11-01 | 2021-11-02 | ... | 2022-10-31
    Equipa A | 09-10 | -1 | 4 | 3 | ... 
    Equipa A | 10-11 | -1 | 4 | 4 | ...
    
    Returns a text string in the format expected by parse_requirements_hourly()
    """
    print(f"\n[LOAD MINIMUMS] Reading from: {mins_csv_file}")
    
    df = pd.read_csv(mins_csv_file, encoding='utf-8')
    
    lines = []
    
    for _, row in df.iterrows():
        row_values = row.values.tolist()
        
        # Find team name (contains "Equipa" or "Team")
        team = None
        hour_range = None
        values_start_idx = None
        
        for idx, val in enumerate(row_values[:5]):  # Check first 5 columns
            val_str = str(val).strip()
            if 'Equipa' in val_str or 'Team' in val_str:
                # Extract team letter (A, B, C, etc.)
                match = re.search(r'([A-Z])$', val_str)
                if match:
                    team = match.group(1)
            elif re.match(r'^\d{2}-\d{2}$', val_str):
                hour_range = val_str
                values_start_idx = idx + 1
                break
        
        if team and hour_range and values_start_idx:
            # Get all values after the hour range
            values = row_values[values_start_idx:]
            # Convert to string, handling NaN
            values_str = ','.join([str(int(v)) if pd.notna(v) and str(v).replace('-','').isdigit() else '-1' for v in values])
            
            # Format: "Team A,min,09-10,val1,val2,val3,..."
            line = f"Team {team},min,{hour_range},{values_str}"
            lines.append(line)
    
    result = '\n'.join(lines)
    print(f"[LOAD MINIMUMS] Loaded {len(lines)} team-hour combinations")
    return result

def load_vacations_from_csv(vacation_csv_file):
    """
    Loads employee vacations from CSV with structure:
    Rows: Employee names (Emp1, Emp2, ...)
    Columns: Days (365 columns, one per day)
    Values: 1 = vacation, 0 = available
    
    Returns a dictionary: {employee_id: [list of 365 values]}
    """
    print(f"\n[LOAD VACATIONS] Reading from: {vacation_csv_file}")
    
    df = pd.read_csv(vacation_csv_file, header=None, encoding='utf-8')
    
    vacations = {}
    
    for _, row in df.iterrows():
        # First column should be employee name
        emp_name = str(row.iloc[0]).strip()
        
        # Extract employee ID from name (e.g., "Emp1" -> 1)
        match = re.search(r'(\d+)', emp_name)
        if match:
            emp_id = int(match.group(1))
            # Get all values (365 days)
            vacation_values = row.iloc[1:].tolist()
            vacations[emp_id] = [int(v) if pd.notna(v) else 0 for v in vacation_values]
    
    print(f"[LOAD VACATIONS] Loaded vacations for {len(vacations)} employees")
    return vacations

def extract_minimums_from_csv(file_path):
    """
    Reads the CSV generated by the algorithm (format EmpX / Day1..Day365)
    and calculates the number of employees per hour, per day, and per team.

    Returns a dictionary in the format:
        {(day_number, '09-10', 'A'): 3, (day_number, '10-11', 'A'): 2, ...}
    """
    df = pd.read_csv(file_path, encoding="utf-8").fillna("")

    # detect day columns
    day_cols = [c for c in df.columns if re.match(r"Day\d+", c, re.IGNORECASE)]
    result = {}

    # extract blocks from each cell
    def parse_block(cell):
        # UPDATED: Handle 3-number format (13-17-22_A) for start-break-end_team
        m = re.match(r"^\s*(\d{1,2})[-_](\d{1,2})[-_](\d{1,2})[_\-]([A-Za-z])\s*$", str(cell).strip())
        if not m:
            return None
        start = int(m.group(1))
        break_h = int(m.group(2))
        end = int(m.group(3))
        team = m.group(4).upper()
        # actually worked hours (without break)
        hours = list(range(start, break_h)) + list(range(break_h + 1, end))
        return hours, team

    for day_col in day_cols:  # iterate over day columns
        day_num = int(re.findall(r"\d+", day_col)[0])

        for _, row in df.iterrows():  # iterate over rows
            cell = row[day_col]  # get cell value
            parsed = parse_block(cell)
            if not parsed:
                continue
            hours, team = parsed  # unpack hours and work team

            for h in hours: 
                key = (day_num, f"{h:02d}-{h+1:02d}", team)  # create unique key
                result[key] = result.get(key, 0) + 1  # {(1, "09-10", "A"): 1}

    return result

def order_minimums(mins_dict, stage="RAW"):
    """
    Orders the minimums dictionary by: Team → Hour → Day
    """
    ordered = dict(sorted(mins_dict.items(), key=lambda x: (x[0][2], x[0][1], x[0][0])))
    
    print(f"\n[ORDER MINIMUMS - {stage}]")
    print(f"  Total keys: {len(ordered)}")
    
    # Print example of result
    print(f"\n  Ordered structure (Team → Hour → Day):")
    current_team = None
    current_hour = None
    for (day, hour, team), count in list(ordered.items())[:30]:  # Show first 30
        if team != current_team:
            if current_team is not None:
                print()
            current_team = team
            current_hour = None
            print(f"  Team {team}:")
        if hour != current_hour:
            current_hour = hour
            print(f"    Hour {hour}:")
        print(f"      Day {day:3d}: {count} employees")
    
    return ordered

def add_feriados_and_sundays(mins_dict, all_teams_and_hours=None):
    """
    Adds entries for missing days (holidays, sundays, etc.) to the dictionary.
    """
    if not mins_dict:
        return mins_dict
    
    # Extract days, hours and teams present
    days_in_dict = set()
    hours_in_dict = set()
    teams_in_dict = set()
    
    for (day, hour, team) in mins_dict.keys():
        days_in_dict.add(day)
        hours_in_dict.add(hour)
        teams_in_dict.add(team)
    
    # Use provided teams/hours or those from dictionary
    if all_teams_and_hours:
        teams_to_use, hours_to_use = all_teams_and_hours
    else:
        teams_to_use = teams_in_dict
        hours_to_use = hours_in_dict
    
    # Find missing days in range 1-365 (full year)
    all_days = set(range(1, 366))  # 1 to 365
    missing_days = sorted(all_days - days_in_dict)
    
    print(f"\n[EXPAND MINIMUMS - ADD FERIADOS & SUNDAYS]")
    print(f"  Missing days: {len(missing_days)} ({missing_days[:15]}...)")
    
    # Add -1 entries for missing days
    added_count = 0
    for daynum in missing_days:
        for team in teams_to_use:
            for hour in hours_to_use:
                key = (daynum, hour, team)
                mins_dict[key] = -1
                added_count += 1
    
    print(f"  Total entries added: {added_count}")
    print(f"  Dictionary size: {len(mins_dict)}")
    
    return mins_dict

def compare_minimums(mins_required, mins_actual):
    """
    Compares required minimums with actual minimums using dictionary keys.
    This ensures proper alignment of (day, hour, team) combinations.
    
    Args:
        mins_required: Dictionary {(day, hour, team): required_count}
        mins_actual: Dictionary {(day, hour, team): actual_count}
    
    Returns:
        int: Total of missed minimums (sum of gaps where gap > 0)
    """
    if not mins_required or not mins_actual:
        return 0
    
    total_gaps = 0
    
    for key, required in mins_required.items():
        # Get actual count for the same (day, hour, team) key
        actual = mins_actual.get(key, 0)
        
        # Skip special days (holidays/sundays marked as -1)
        if required == -1 or actual == -1:
            continue
        
        # Skip string values (safety check)
        if isinstance(required, str) or isinstance(actual, str):
            continue
        
        gap = required - actual
        if gap > 0:
            total_gaps += gap
    
    return total_gaps

def filter_holidays_by_schedule_range(holidays, schedule_start_date, schedule_end_date):
    """
    Filters holidays to only include those within the schedule date range.
    
    Args:
        holidays: set/list/dict of holiday dates
        schedule_start_date: datetime.date object for schedule start
        schedule_end_date: datetime.date object for schedule end
    
    Returns:
        set of datetime.date objects within the range
    """
    holidays_set = set()
    
    # If it's a dictionary (from holidays.country_holidays), use keys
    if isinstance(holidays, dict):
        holidays_iterable = holidays.keys()
    else:
        holidays_iterable = holidays
    
    for h in holidays_iterable:
        try:
            if isinstance(h, datetime):
                d = h.date()
            elif isinstance(h, date):
                d = h
            else:
                d = pd.to_datetime(str(h)).date()
            
            # Only include if within schedule range
            if schedule_start_date <= d <= schedule_end_date:
                holidays_set.add(d)
        except Exception as e:
            print(f"[WARNING] Failed to parse holiday {h}: {e}")
    
    print(f"[FILTER HOLIDAYS] Filtered from {len(list(holidays_iterable))} to {len(holidays_set)} holidays")
    print(f"  Schedule range: {schedule_start_date} to {schedule_end_date}")
    print(f"  Holidays in range: {sorted(holidays_set)}")
    
    return holidays_set

def analyze(file, holidays, mins, employees, year=2025):
    """
    Analyzes schedule file (each cell ex.: '9-18_A' or '09-18_A' or 'VACATION' / 'F').
    - holidays: set of year days (1-based) or set of datetime.dates.
    - mins: CSV text of requirements per hour.
    - employees: JSON string or list of dicts with "name" and "teams".
    """

    print(f"[DEBUG] Entering analyze() in kpiVerification_Hours with {file}")
    print(f"[KPI Hours] Analyzing hourly file: {file}")
    
    # Read CSV to detect schedule date range
    df_temp = pd.read_csv(file, encoding='ISO-8859-1', dtype=str, nrows=0)
    dia_cols_temp = [c for c in df_temp.columns if re.match(r'^(Dia|Day)\s*\d+$', c, flags=re.I)]
    if not dia_cols_temp:
        dia_cols_temp = [c for c in df_temp.columns if c.lower().startswith("dia") or c.lower().startswith("day")]
    
    # Extract day numbers from columns
    day_numbers = []
    for c in dia_cols_temp:
        m = re.search(r'(\d+)', c)
        if m:
            day_numbers.append(int(m.group(1)))
    
    if day_numbers:
        min_day = min(day_numbers)
        max_day = max(day_numbers)
        # Assuming Day 1 = November 1, 2021 (you can adjust this base date)
        schedule_start_date = date(2021, 11, 1) + pd.Timedelta(days=min_day - 1)
        schedule_end_date = date(2021, 11, 1) + pd.Timedelta(days=max_day - 1)
        
        print(f"[SCHEDULE RANGE] Detected from CSV columns:")
        print(f"  Day range: {min_day} to {max_day}")
        print(f"  Date range: {schedule_start_date} to {schedule_end_date}")
        
        # Filter holidays to only those within schedule range
        holidays = filter_holidays_by_schedule_range(holidays, schedule_start_date, schedule_end_date)
    else:
        print("[WARNING] Could not detect day columns, using all holidays")
        schedule_start_date = date(2021, 11, 1)
        schedule_end_date = date(2022, 10, 31)

    # --------------------------- Process Minimums ---------------------------

    # Extract actual coverage from schedule
    mins_F = extract_minimums_from_csv(file)
    mins_F_Ordered = order_minimums(
        mins_F,
        stage="RAW (WITHOUT HOLIDAYS / SUNDAYS)"
    )
    print(f"[DEBUG] Ordered minimums (RAW) sample: {list(mins_F_Ordered.items())[:200]}")

    # Add missing days (holidays, sundays)
    mins_with_holidays = add_feriados_and_sundays(mins_F_Ordered)
    
    # Re-order after adding missing days to keep everything organized
    mins_final_ordered = order_minimums(
        mins_with_holidays,
        stage="FINAL (WITH HOLIDAYS & SUNDAYS)"
    )
    print(f"[DEBUG] Ordered minimums (FINAL, with holidays) sample: {list(mins_final_ordered.items())[:200]}")

    # Convert to list for debugging
    mins_final_list = list(mins_final_ordered.values())
    print(f"[DEBUG] Final mins list sample: {mins_final_list[:200]}")
    
    # Parse required minimums from CSV and order them
    mins_required_dict, ideals_required_dict = parse_requirements_hourly(mins)
    mins_required_ordered = order_minimums(mins_required_dict)
    
    
    # Calculate coverage gaps and overstaff using key-based lookup
    hourlyCoverageGaps = 0
    hourlyOverstaff = 0
    
    # Debug collections
    overstaff_details = []
    gap_details = []
    
    for key, actual_count in mins_final_ordered.items():
        # Get required count for the same (day, hour, team) key
        required = mins_required_ordered.get(key, 0)
        
        # Skip special days (marked as -1)
        if required == -1 or actual_count == -1:
            continue
        
        gap = required - actual_count
        if gap > 0:
            hourlyCoverageGaps += gap
            gap_details.append((key, required, actual_count, gap))
        elif gap < 0:
            hourlyOverstaff += abs(gap)
            overstaff_details.append((key, required, actual_count, abs(gap)))
    
    
    # Calculate minimums gaps using dictionary-based comparison
    missed_team_min = compare_minimums(mins_required_ordered, mins_final_ordered)
    
    # Ideals: only calculate if we actually have ideal values
    has_ideals = len(ideals_required_dict) > 0
    if has_ideals:
        ideals_required_ordered = order_minimums(ideals_required_dict)
        missed_team_ideal = compare_minimums(ideals_required_ordered, mins_final_ordered)
    else:
        missed_team_ideal = 0
        print("[INFO] No ideal requirements provided - missedTeamIdeal set to 0")

    print(f"[DEBUG] Minimums Missed (CORRECTED): {missed_team_min}")
    print(f"[DEBUG] Coverage Gaps (for verification): {hourlyCoverageGaps}")
    print(f"[DEBUG] Overstaff: {hourlyOverstaff}")
    
    # Verify that both methods give the same result
    if missed_team_min != hourlyCoverageGaps:
        print(f"[WARNING] Discrepancy detected!")
        print(f"  compare_minimums result: {missed_team_min}")
        print(f"  hourlyCoverageGaps result: {hourlyCoverageGaps}")
        print(f"  Difference: {abs(missed_team_min - hourlyCoverageGaps)}")

   
    # --------------------------- Process Schedule DataFrame ---------------------------

    df = pd.read_csv(file, encoding='ISO-8859-1', dtype=str).fillna("")

    # Normalize employee column name
    col_names_lower = [c.lower() for c in df.columns]
    employee_col = None
    
    # Search for employee column name variations
    if any("employee" in c.lower() for c in col_names_lower):
        employee_col = next(c for c in df.columns if "employee" in c.lower())
    elif any("funcionario" in c.lower() for c in col_names_lower):
        employee_col = next(c for c in df.columns if "funcionario" in c.lower())
    elif any("emp" in c.lower() for c in col_names_lower):
        employee_col = next(c for c in df.columns if "emp" in c.lower())
    else:
        # fallback: assume first column is employee identifier
        employee_col = df.columns[0]
    
    # Rename to internal standard
    if employee_col != "Employee":
        df.rename(columns={employee_col: "Employee"}, inplace=True)
    
    print(f"[KPI Hours] Employee column detected: {employee_col}")

    # Helpers --------------------------------------------------------------
    def parse_block(val):
        """
        Extracts (start, end, team) from cells.
        UPDATED: Now handles 3-number format like '13-17-22_A' (start-break-end_team)
        """
        if not isinstance(val, str):
            return (None, None, None)
        # Match 3-number format: 13-17-22_A
        m = re.match(r'^\s*(\d{1,2})\s*-\s*(\d{1,2})\s*-\s*(\d{1,2})\s*[_\-]\s*([A-Za-z])\s*$', val.strip())
        if m:
            return int(m.group(1)), int(m.group(3)), m.group(4).upper()
        return (None, None, None)

    def is_work_block(val):
        s, e, t = parse_block(val)
        return s is not None and e is not None and t is not None

    # Initialize KPI counters ----------------------------------------------
    missed_work_days = 0
    missed_vacation_days = 0
    workHolidays = 0
    consecutiveDays = 0
    team_satisfaction_values = []
    
    # Parse employee teams
    teams = parse_employees(employees)
    print(f"[DEBUG] Parsed teams for employees: {list(teams.items())[:5]}")

    # holidays already filtered at the beginning of analyze()
    holidays_set = holidays if isinstance(holidays, set) else set(holidays)
    print(f"[DEBUG] Using filtered holidays_set: {sorted(list(holidays_set))[:5]} ... total={len(holidays_set)}")

    # Day columns
    dia_cols = [c for c in df.columns if re.match(r'^(Dia|Day)\s*\d+$', c, flags=re.I)]
    if not dia_cols:
        dia_cols = [c for c in df.columns if c.lower().startswith("dia") or c.lower().startswith("day")]

    # Map column → day number
    col_to_day = {}
    for c in dia_cols:
        m = re.search(r'(\d+)', c)
        if m:
            col_to_day[c] = int(m.group(1))
        else:
            col_to_day[c] = len(col_to_day) + 1

    # Create map of day numbers to real dates
    start_date = date(2021, 11, 1)
    daynum_to_date = {}
    for daynum in col_to_day.values():
        daynum_to_date[daynum] = start_date + pd.Timedelta(days=daynum - 1)

    # Special columns (holidays): compare real dates
    all_special_cols = [col for col, daynum in col_to_day.items() 
                        if daynum in daynum_to_date and daynum_to_date[daynum] in holidays_set]

    print(f"[DEBUG] Holiday columns detected: {all_special_cols}")

    """
    # Process each employee row ----------------------------------------------
    for _, row in df.iterrows():
        try:
            emp_val = row.get("Employee", row.iloc[0] if len(row) > 0 else None)
            emp_id = None
            if isinstance(emp_val, str):
                m = re.search(r'(\d+)', emp_val)
                if m:
                    emp_id = int(m.group(1))
            else:
                try:
                    emp_id = int(emp_val)
                except Exception:
                    emp_id = None
        except Exception as e:
            print(f"[WARNING] Error parsing employee row: {e}")
            continue

        # Day counts
        worked_days = sum(1 for c in dia_cols if c in row.index and is_work_block(row[c]))
        vacation_days = sum(1 for c in dia_cols if c in row.index and str(row[c]).strip().upper() in ("F", "VACATION"))

        missed_work_days += abs(223 - worked_days)
        missed_vacation_days += abs(30 - vacation_days)

        # KPI: Worked holidays/sundays (generic) - maximum 22 per employee per year
        total_worked_holidays = sum(1 for c in all_special_cols if c in row.index and is_work_block(row[c]))
        if total_worked_holidays > 22:
            workHolidays += (total_worked_holidays - 22)

        """
    
        # Process each employee row ----------------------------------------------
    # Debug counters
    debug_work_holidays = []

    for _, row in df.iterrows():
        try:
            emp_val = row.get("Employee", row.iloc[0] if len(row) > 0 else None)
            emp_id = None
            if isinstance(emp_val, str):
                m = re.search(r'(\d+)', emp_val)
                if m:
                    emp_id = int(m.group(1))
            else:
                try:
                    emp_id = int(emp_val)
                except Exception:
                    emp_id = None
        except Exception as e:
            print(f"[WARNING] Error parsing employee row: {e}")
            continue

        # Day counts
        worked_days = sum(1 for c in dia_cols if c in row.index and is_work_block(row[c]))
        vacation_days = sum(1 for c in dia_cols if c in row.index and str(row[c]).strip().upper() in ("F", "VACATION"))

        missed_work_days += abs(223 - worked_days)
        missed_vacation_days += abs(30 - vacation_days)

        # KPI: Worked holidays/sundays - DEBUG VERSION
        total_worked_holidays = sum(1 for c in all_special_cols if c in row.index and is_work_block(row[c]))
        
        # Debug: show details for this employee
        if total_worked_holidays > 0:
            worked_holiday_details = []
            for c in all_special_cols:
                if c in row.index and is_work_block(row[c]):
                    daynum = col_to_day.get(c)
                    real_date = daynum_to_date.get(daynum) if daynum else None
                    worked_holiday_details.append((c, daynum, real_date, row[c]))
            
            debug_work_holidays.append({
                'emp_id': emp_id,
                'total': total_worked_holidays,
                'details': worked_holiday_details
            })
        
        if total_worked_holidays > 22:
            workHolidays += (total_worked_holidays - 22)

        # 6+ consecutive work days
        work_seq = [1 if c in row.index and is_work_block(row[c]) else 0 for c in dia_cols]
        streak = 0
        max_streak = 0
        fails = 0
        for v in work_seq:
            if v:
                streak += 1
                if streak > max_streak:
                    max_streak = streak
                if streak >= 6:
                    fails += 1
            else:
                streak = 0

        print(f"[DEBUG][consecutiveDays] Emp={emp_id} | max_streak={max_streak} | fails={fails}")

        consecutiveDays += fails

        # KPI: Team satisfaction (only if employees have preferences)
        allowed_codes = teams.get(emp_id, []) if emp_id is not None else []
        team_counts = {}
        for c in dia_cols:
            if c in row.index:
                _, _, t = parse_block(row[c])
                if t:
                    team_counts[t] = team_counts.get(t, 0) + 1

        if len(allowed_codes) >= 1:
            total_worked = sum(team_counts.values())
            if total_worked > 0:
                preferred = allowed_codes[0]
                pref_count = team_counts.get(preferred, 0)
                team_satisfaction_values.append(round((pref_count / total_worked) * 100, 2))



    # Print debug info after loop
    print(f"\n[DEBUG WORK HOLIDAYS]")
    print(f"  Total special columns (holidays/sundays): {len(all_special_cols)}")
    print(f"  Special columns: {all_special_cols[:10]}..." if len(all_special_cols) > 10 else f"  Special columns: {all_special_cols}")
    print(f"  Employees who worked on holidays/sundays: {len(debug_work_holidays)}")

    if debug_work_holidays:
        print(f"\n  Top 5 employees with most worked holidays:")
        sorted_debug = sorted(debug_work_holidays, key=lambda x: x['total'], reverse=True)[:5]
        for emp_data in sorted_debug:
            print(f"    Employee {emp_data['emp_id']}: {emp_data['total']} holidays worked")
            for col, daynum, real_date, shift_val in emp_data['details'][:10]:
                print(f"      - Day {daynum} ({real_date}): {shift_val}")
    else:
        print(f"  No employees worked on holidays/sundoms")

    print(f"  Total workHolidays violations (>22): {workHolidays}")

    # Calculate final metrics ----------------------------------------------
    team_satisfaction = (
        round(sum(team_satisfaction_values) / len(team_satisfaction_values), 2)
        if team_satisfaction_values
        else 0
    )

    # Print debug info
    print(f"\n[DEBUG WORK HOLIDAYS]")
    print(f"  Total special columns (holidays/sundays): {len(all_special_cols)}")
    print(f"  Special columns: {all_special_cols[:10]}..." if len(all_special_cols) > 10 else f"  Special columns: {all_special_cols}")
    print(f"  Employees who worked on holidays/sundays: {len(debug_work_holidays)}")
    
    if debug_work_holidays:
        print(f"\n  Top 5 employees with most worked holidays:")
        sorted_debug = sorted(debug_work_holidays, key=lambda x: x['total'], reverse=True)[:5]
        for emp_data in sorted_debug:
            print(f"    Employee {emp_data['emp_id']}: {emp_data['total']} holidays worked")
            for col, daynum, real_date, shift_val in emp_data['details'][:3]:
                print(f"      - Day {daynum} ({real_date}): {shift_val}")
    else:
        print(f"  No employees worked on holidays/sundays")
    
    print(f"  Total workHolidays violations (>22): {workHolidays}")

    
    # Calculate final metrics
    team_satisfaction = (
        round(sum(team_satisfaction_values) / len(team_satisfaction_values), 2)
        if team_satisfaction_values
        else 0
    )

    return {
        "missedWorkDays": missed_work_days,
        "missedVacationDays": missed_vacation_days,
        "workHolidays": workHolidays,
        "consecutiveDays": consecutiveDays,
        "missedTeamMin": missed_team_min,
        "missedTeamIdeal": missed_team_ideal if has_ideals else 0,
        "teamSatisfactionLevel": team_satisfaction,
        "hourlyCoverageGaps": hourlyCoverageGaps,
        "hourlyOverstaff": hourlyOverstaff
    }


# ----------------------------------------------------------------------
def parse_requirements_hourly(requirements_text):
    mins, ideals = {}, {}
    if not requirements_text:
        print("[DEBUG] parse_requirements_hourly: empty input")
        return mins, ideals

    print(f"[DEBUG] parse_requirements_hourly: raw length={len(str(requirements_text))}")
    
    # Normalize separators and newlines
    text = requirements_text.replace('\r', '\n').replace(';', ',').strip()
    lines = [l for l in text.split('\n') if l.strip()]
    print(f"[DEBUG] Lines detected: {len(lines)}")
    
    # If everything is in one line, try to force split by "Team" keywords or patterns
    if len(lines) == 1:
        long_line = lines[0]
        chunks = re.split(r'(?=[A-Z]\s*,)', long_line)
        lines = [l.strip() for l in chunks if l.strip()]
        print(f"[DEBUG] Split long line into {len(lines)} logical entries")

    for line in lines:
        parts = [p.strip() for p in line.split(',')]
        if len(parts) < 4:
            continue
        
        # Detect pattern like "Equipa A,09-10"
        if len(parts) >= 3 and ("Equipa" in parts[1] or "Team" in parts[1]):
            team_code = parts[1].split()[-1].upper().strip()
            hour_range = parts[2]
            values = parts[3:]
            target = mins
        elif len(parts) >= 3 and re.match(r'^\d{2}-\d{2}$', parts[1]):
            team_code = parts[0].split()[-1].upper().strip()
            hour_range = parts[1]
            values = parts[2:]
            target = mins
        else:
            team_label_raw, req_type, hour_range = parts[:3]
            values = parts[3:]
            team_match = re.search(r'([A-Za-z])$', team_label_raw)
            if not team_match:
                print(f"[DEBUG] Skipping invalid team_label: {team_label_raw}")
                continue
            team_code = team_match.group(1).upper()
            target = mins if 'min' in req_type.lower() else ideals

        for day_idx, val in enumerate(values, start=1):
            val_str = str(val).strip()
            if val_str.lstrip('-').isdigit():
                target[(day_idx, hour_range, team_code)] = int(val_str)
    
    print(f"[CHECK] Total mins={len(mins)} ideals={len(ideals)}")
    print(f"[CHECK] Sample mins: {list(mins.keys())[:10]}")

    return mins, ideals

# ----------------------------------------------------------------------
def parse_employees(employees_json):
    teams = {}
    if not employees_json:
        return teams
    if isinstance(employees_json, str):
        try:
            employees_list = json.loads(employees_json)
        except Exception:
            employees_list = []
    else:
        employees_list = employees_json

    for emp in employees_list:
        name = emp.get("name", "")
        m = re.search(r'(\d+)', str(name))
        emp_id = int(m.group(1)) if m else emp.get("id", None)
        if emp_id is None:
            continue
        codes = []
        for t in emp.get("teams", []):
            mt = re.search(r'([A-Za-z])\s*$', str(t))
            if mt:
                codes.append(mt.group(1).upper())
        seen = set()
        codes = [c for c in codes if not (c in seen or seen.add(c))]
        teams[int(emp_id)] = codes
    return teams

def generate_employees_from_vacation_csv(vacation_csv_file):
    """
    Generates a basic employees JSON structure from the vacation CSV.
    Assumes all employees can work in both Team A and Team B.
    
    Returns: List of dicts with format [{"name": "Employee 1", "teams": ["Team A", "Team B"]}, ...]
    """
    print(f"\n[GENERATE EMPLOYEES] Extracting from: {vacation_csv_file}")
    
    df = pd.read_csv(vacation_csv_file, header=None, encoding='utf-8')
    
    employees = []
    for _, row in df.iterrows():
        emp_name = str(row.iloc[0]).strip()
        # Verify it's an employee name
        if re.match(r'Employee\s*\d+', emp_name, re.IGNORECASE):
            employees.append({
                "name": emp_name,
                "teams": ["Team A", "Team B"]
            })
    
    print(f"[GENERATE EMPLOYEES] Created {len(employees)} employee records")
    return employees

# ----------------------------------------------------------------------
# LOCAL TESTING MAIN
# ----------------------------------------------------------------------
if __name__ == "__main__":
    print("="*80)
    print("LOCAL TESTING MODE - kpiVerification_HoursLocal.py")
    print("="*80)
    
    # Configuration for local testing
    #CSV_FILE = "Horário_Por_Intervalos_1Hora.csv"
    CSV_FILE = "Horário_Por_Intervalos_1Hora_7hours_to_run.csv"
    MINS_CSV = "Mins_R10-R62.csv"
    VACATION_CSV = "VacationTemplate_Case1_21.csv"
    
    # Generate Portuguese holidays for 2021-2022 period
    pt_holidays = holidays.Portugal(years=[2021, 2022])
    holidays_list = list(pt_holidays.keys())
    
    print(f"\nReading schedule CSV: {CSV_FILE}")
    print(f"Reading minimums CSV: {MINS_CSV}")
    print(f"Reading vacations CSV: {VACATION_CSV}")
    print(f"Public holidays: {len(holidays_list)} defined")
    print("\n" + "="*80)
    
    try:
        # Load minimums from CSV
        minimums_text = load_minimums_from_csv(MINS_CSV)
        
        # Load vacations from CSV (for reference, not used in current KPI logic)
        vacations_dict = load_vacations_from_csv(VACATION_CSV)
        
        # Generate employees JSON from vacation CSV
        employees_data = generate_employees_from_vacation_csv(VACATION_CSV)
        
        print(f"\nConfiguration loaded successfully:")
        print(f"  Minimums lines: {len(minimums_text.split(chr(10)))}")
        print(f"  Employees: {len(employees_data)}")
        print(f"  Vacations loaded for: {len(vacations_dict)} employees")
        
        # Call analyze function
        kpi_results = analyze(
            file=CSV_FILE,
            holidays=holidays_list,
            mins=minimums_text,
            employees=employees_data,
            year=2021
        )
        
        print("\n" + "="*80)
        print("KPI RESULTS")
        print("="*80)
        for key, value in kpi_results.items():
            print(f"{key:30s}: {value}")
        print("="*80)
        
    except FileNotFoundError as e:
        print(f"\n[ERROR] File not found: {e}")
        print("Please ensure all CSV files exist in the same directory as this script:")
        print(f"  - {CSV_FILE}")
        print(f"  - {MINS_CSV}")
        print(f"  - {VACATION_CSV}")
    except Exception as e:
        print(f"\n[ERROR] Exception occurred: {e}")
        traceback.print_exc()