import traceback
import pandas as pd
import re
import json
from datetime import date, datetime

def extract_minimums_from_csv(file_path):
    """
    Reads the CSV generated by the algorithm (format EmpX / Day1..Day365)
    and calculates the number of employees per hour, per day, and per team.

    Returns a dictionary in the format:
        {(day_number, '09-10', 'A'): 3, (day_number, '10-11', 'A'): 2, ...}
    """
    df = pd.read_csv(file_path, encoding="utf-8")
    df = df.fillna("")

    # detect day columns
    day_cols = [c for c in df.columns if re.match(r"Day\d+", c, re.IGNORECASE)]
    result = {}

    # extract blocks from each cell
    def parse_block(cell):
        m = re.match(r"^\s*(\d{1,2})[-_](\d{1,2})[-_](\d{1,2})[_\-]([A-Za-z])\s*$", str(cell).strip())
        if not m:
            return None
        start = int(m.group(1))
        break_h = int(m.group(2))
        end = int(m.group(3))
        team = m.group(4).upper()
        # actually worked hours (without break)
        hours = list(range(start, break_h)) + list(range(break_h + 1, end))
        return hours, team

    for day_col in day_cols:  # iterate over day columns
        day_num = int(re.findall(r"\d+", day_col)[0])
        for _, row in df.iterrows():  # iterate over rows
            cell = row[day_col]  # get cell value
            parsed = parse_block(cell)
            if not parsed:
                continue
            hours, team = parsed  # unpack hours and work team
            for h in hours: 
                key = (day_num, f"{h:02d}-{h+1:02d}", team)  # create unique key
                result[key] = result.get(key, 0) + 1  # {(1, "09-10", "A"): 1}

    return result

def order_minimums(mins_dict):
    """
    Orders the minimums dictionary by: Team → Hour → Day
    
    Input:  {(362, '20-21', 'A'): 4, (363, '14-15', 'B'): 8, ...}
    
    Output: Ordered as:
        - Team A, 09-10: [day 1, day 2, day 3, ..., day 365]
        - Team A, 10-11: [day 1, day 2, day 3, ..., day 365]
        - ...
        - Team B, 09-10: [day 1, day 2, day 3, ..., day 365]
        - ...
    
    Ordering: key[2] (Team), key[1] (Hour), key[0] (Day)
    """
    # Sort by: Team (3rd element), then Hour (2nd element), then Day (1st element)
    ordered = dict(sorted(mins_dict.items(), key=lambda x: (x[0][2], x[0][1], x[0][0])))
    
    print(f"\n[ORDER MINIMUMS]")
    print(f"  Total keys: {len(ordered)}")
    
    # Print example of result
    print(f"\n  Ordered structure (Team → Hour → Day):")
    current_team = None
    current_hour = None
    for (day, hour, team), count in list(ordered.items())[:30]:  # Show first 30
        if team != current_team:
            if current_team is not None:
                print()
            current_team = team
            current_hour = None
            print(f"  Team {team}:")
        if hour != current_hour:
            current_hour = hour
            print(f"    Hour {hour}:")
        print(f"      Day {day:3d}: {count} employees")
    
    return ordered

def add_feriados_and_sundays(mins_dict, all_teams_and_hours=None):
    """
    Adds entries for missing days (holidays, sundays, etc.) to the dictionary.
    Missing days are those that don't appear in the dictionary.
    For each missing day adds an entry with value -1 for all (hour, team).
    
    Args:
        mins_dict: Dictionary with format {(day, 'HH-MM', team): count}
        all_teams_and_hours: Optional. Tuple (teams_set, hours_set) to force teams/hours.
                            If None, uses those found in mins_dict.
    
    Returns:
        mins_dict: Updated dictionary with -1 entries for missing days (1-365)
    """
    
    if not mins_dict:
        return mins_dict
    
    # Extract days, hours and teams present
    days_in_dict = set()
    hours_in_dict = set()
    teams_in_dict = set()
    
    for (day, hour, team) in mins_dict.keys():
        days_in_dict.add(day)
        hours_in_dict.add(hour)
        teams_in_dict.add(team)
    
    # Use provided teams/hours or those from dictionary
    if all_teams_and_hours:
        teams_to_use, hours_to_use = all_teams_and_hours
    else:
        teams_to_use = teams_in_dict
        hours_to_use = hours_in_dict
    
    # Find missing days in range 1-365 (full year)
    all_days = set(range(1, 366))  # 1 to 365
    missing_days = sorted(all_days - days_in_dict)
    
    print(f"\n[ADD FERIADOS & SUNDAYS]")
    print(f"  Days present: {len(days_in_dict)} / 365")
    print(f"  Teams to cover: {sorted(teams_to_use)}")
    print(f"  Hours to cover: {sorted(hours_to_use)}")
    print(f"  Missing days: {len(missing_days)} ({missing_days[:15]}...)")
    
    # Add -1 entries for missing days
    added_count = 0
    for daynum in missing_days:
        for team in teams_to_use:
            for hour in hours_to_use:
                key = (daynum, hour, team)
                mins_dict[key] = -1
                added_count += 1
    
    print(f"  Total entries added: {added_count}")
    print(f"  Dictionary size: {len(mins_dict)}")
    print(f"Dictionary sample after adding missing days: {list(mins_dict.items())}")
    
    return mins_dict

def compare_minimums(mins_required, mins_actual):
    """
    Compares lists of required minimums with actual minimums.
    Returns only the total of missed minimums (coverage gaps).
    
    Args:
        mins_required: List of ordered values [required1, required2, ...]
        mins_actual: List of ordered values [actual1, actual2, ...]
    
    Returns:
        int: Total of missed minimums (sum of gaps where gap > 0)
    
    Example:
        mins_required = [-1, 10, 8, -1, 6]
        mins_actual   = [-1,  8, 8, -1, 6]
        
        Return: 2 (gap of 2 at position 1)
    """
    if not mins_required or not mins_actual:
        return 0
    
    total_gaps = 0
    min_length = min(len(mins_required), len(mins_actual))
    
    for i in range(min_length):
        if isinstance(mins_required[i], str) or isinstance(mins_actual[i], str):
            continue
        gap = mins_required[i] - mins_actual[i]
        if gap > 0:
            total_gaps += gap
    
    return total_gaps

def analyze(file, holidays, mins, employees, year=2025):
    """
    Analyzes schedule file (each cell ex.: '9-18_A' or '09-18_A' or 'VACATION' / 'F').
    - holidays: set of year days (1-based) or set of datetime.dates.
    - mins: CSV text of requirements per hour.
    - employees: JSON string or list of dicts with "name" and "teams".
    """

    print(f"[DEBUG] Entering analyze() in kpiVerification_Hours with {file}")
    print(f"[KPI Hours] Analyzing hourly file: {file}")

    # --------------------------- Minimums ---------------------------

    mins_F = extract_minimums_from_csv(file)

    mins_F_Ordered = order_minimums(mins_F)
    print(f"[DEBUG] Ordered mins_F sample: {list(mins_F_Ordered.items())[:200]}")

    mins_with_holidays = add_feriados_and_sundays(mins_F_Ordered)
    
    # Re-order after adding missing days to keep everything organized
    mins_final_ordered = order_minimums(mins_with_holidays)
    print(f"[DEBUG] Mins with holidays (final ordered) sample: {list(mins_final_ordered.items())[:200]}")

    mins_final_list = list(mins_final_ordered.values())
    print(f"[DEBUG] Final mins list sample: {mins_final_list[:200]}")
    
    missed_team_min = compare_minimums(mins, mins_final_list)

    print(f"[DEBUG] Minimums Missed: {missed_team_min}")

    # --------------------------- xxx ---------------------------

    df = pd.read_csv(file, encoding='ISO-8859-1', dtype=str).fillna("")

    # Normalize employee column name
    col_names_lower = [c.lower() for c in df.columns]
    employee_col = None
    
    # Search for employee column name variations
    if any("employee" in c.lower() for c in col_names_lower):
        employee_col = next(c for c in df.columns if "employee" in c.lower())
    elif any("funcionario" in c.lower() for c in col_names_lower):
        employee_col = next(c for c in df.columns if "funcionario" in c.lower())
    elif any("emp" in c.lower() for c in col_names_lower):
        employee_col = next(c for c in df.columns if "emp" in c.lower())
    else:
        # fallback: assume first column is employee identifier
        employee_col = df.columns[0]
    
    # Rename to internal standard
    if employee_col != "Employee":
        df.rename(columns={employee_col: "Employee"}, inplace=True)
    
    print(f"[KPI Hours] Employee column detected: {employee_col}")

    # Helpers --------------------------------------------------------------
    def parse_block(val):
        """
        Extracts (start, end, team) from cells like '9-18_A' or '09-18-A'.
        """
        if not isinstance(val, str):
            return (None, None, None)
        m = re.match(r'^\s*(\d{1,2})\s*-\s*(\d{1,2})\s*[_\-]\s*([A-Za-z])\s*$', val.strip())
        if m:
            return int(m.group(1)), int(m.group(2)), m.group(3).upper()
        return (None, None, None)

    def is_work_block(val):
        s, e, t = parse_block(val)
        return s is not None and e is not None and t is not None

    # ----------------------------------------------------------------------
    missed_work_days = 0
    missed_vacation_days = 0
    missed_team_min = 0
    missed_team_ideal = 0
    workHolidays = 0
    consecutiveDays = 0
    single_team_violations = 0
    team_satisfaction_values = []
    hourlyCoverageGaps = 0
    hourlyOverstaff = 0

    mins_dict, ideals_dict = parse_requirements_hourly(mins)
    print(f"[DEBUG] mins_dict keys sample: {list(mins_dict.keys())[:5]}")
    print(f"[DEBUG] ideals_dict keys sample: {list(ideals_dict.keys())[:5]}")
    teams = parse_employees(employees)
    print(f"[DEBUG] Parsed teams for employees: {list(teams.items())[:5]}")

    # Normalize holidays to set of dates (datetime.date objects)
    # Keeps original dates without converting to day-of-year
    holidays_set = set()
    if holidays:
        print(f"[DEBUG] Input holidays type: {type(holidays).__name__}")
        
        # If it's a dictionary (from hl.country_holidays), use keys
        if isinstance(holidays, dict):
            holidays_iterable = holidays.keys()
        else:
            holidays_iterable = holidays

        for h in holidays_iterable:
            try:
                print(f"[DEBUG] Processing holiday {h} of type {type(h).__name__}")
                
                if isinstance(h, datetime):
                    # datetime.datetime: extract date
                    d = h.date()
                    print(f"  → Converting datetime to date: {d}")
                    holidays_set.add(d)
                elif isinstance(h, date):
                    # datetime.date: add directly
                    print(f"  → Adding date directly: {h}")
                    holidays_set.add(h)
                elif isinstance(h, int):
                    # If integer, assume it's day-of-year and try to convert
                    # (compatibility with old data)
                    print(f"  → Skipping int (day-of-year not supported in this context): {h}")
                    continue
                else:
                    # Fallback: try to convert string/other format to date
                    print(f"  → Fallback: converting {type(h).__name__} to date")
                    d = pd.to_datetime(str(h)).date()
                    print(f"  → Converted to date: {d}")
                    holidays_set.add(d)
            except Exception as e:
                print(f"[ERROR] Failed to normalize holiday value {h} (type={type(h).__name__}): {e}")
                import traceback
                traceback.print_exc()

    print(f"[DEBUG] Normalized holidays_set (dates): {sorted(list(holidays_set))[:5]} ... total={len(holidays_set)}")

    # Day columns
    dia_cols = [c for c in df.columns if re.match(r'^(Dia|Day)\s*\d+$', c, flags=re.I)]
    if not dia_cols:
        dia_cols = [c for c in df.columns if c.lower().startswith("dia") or c.lower().startswith("day")]

    # Map column → day number
    col_to_day = {}
    for c in dia_cols:
        m = re.search(r'(\d+)', c)
        if m:
            col_to_day[c] = int(m.group(1))
        else:
            col_to_day[c] = len(col_to_day) + 1

    # Create map of day numbers to real dates
    # Assuming day 1 is November 1, 2021
    start_date = date(2021, 11, 1)
    daynum_to_date = {}
    for daynum in col_to_day.values():
        daynum_to_date[daynum] = start_date + pd.Timedelta(days=daynum - 1)

    # Special columns (holidays): compare real dates
    all_special_cols = [col for col, daynum in col_to_day.items() 
                        if daynum in daynum_to_date and daynum_to_date[daynum] in holidays_set]

    print(f"[DEBUG] Holiday columns detected: {all_special_cols}")

    # ----------------------------------------------------------------------
    for _, row in df.iterrows():
        try:
            emp_val = row.get("Employee", row.iloc[0] if len(row) > 0 else None)
            emp_id = None
            if isinstance(emp_val, str):
                m = re.search(r'(\d+)', emp_val)
                if m:
                    emp_id = int(m.group(1))
            else:
                try:
                    emp_id = int(emp_val)
                except Exception:
                    emp_id = None
        except Exception as e:
            print(f"[WARNING] Error parsing employee row: {e}")
            continue

        # Day counts
        worked_days = sum(1 for c in dia_cols if c in row.index and is_work_block(row[c]))
        vacation_days = sum(1 for c in dia_cols if c in row.index and str(row[c]).strip().upper() in ("F", "VACATION"))

        missed_work_days += abs(223 - worked_days)
        missed_vacation_days += abs(30 - vacation_days)

        total_worked_holidays = sum(1 for c in all_special_cols if c in row.index and is_work_block(row[c]))
        if total_worked_holidays > 22:
            workHolidays += (total_worked_holidays - 22)

        # 6+ consecutive work days
        work_seq = [1 if c in row.index and is_work_block(row[c]) else 0 for c in dia_cols]
        streak = 0
        fails = 0
        for v in work_seq:
            if v:
                streak += 1
                if streak >= 6:
                    fails += 1
            else:
                streak = 0
        consecutiveDays += fails

        # Teams
        allowed_codes = teams.get(emp_id, []) if emp_id is not None else []
        team_counts = {}
        for c in dia_cols:
            if c in row.index:
                _, _, t = parse_block(row[c])
                if t:
                    team_counts[t] = team_counts.get(t, 0) + 1

        if len(allowed_codes) == 1:
            allowed = set(allowed_codes)
            worked = set(team_counts.keys())
            if worked - allowed:
                single_team_violations += 1

        if len(allowed_codes) >= 1:
            total_worked = sum(team_counts.values())
            if total_worked > 0:
                preferred = allowed_codes[0]
                pref_count = team_counts.get(preferred, 0)
                team_satisfaction_values.append(round((pref_count / total_worked) * 100, 2))

    # ----------------------------------------------------------------------
    team_satisfaction = (
        round(sum(team_satisfaction_values) / len(team_satisfaction_values), 2)
        if team_satisfaction_values
        else 0
    )

    return {
        "missedWorkDays": missed_work_days,
        "missedVacationDays": missed_vacation_days,
        "workHolidays": workHolidays,
        "consecutiveDays": consecutiveDays,
        "singleTeamViolations": single_team_violations,
        "missedTeamMin": missed_team_min,
        "missedTeamIdeal": missed_team_ideal,
        "teamSatisfactionLevel": team_satisfaction,
        "hourlyCoverageGaps": hourlyCoverageGaps,
        "hourlyOverstaff": hourlyOverstaff
    }

# ----------------------------------------------------------------------
def parse_requirements_hourly(requirements_text):
    mins, ideals = {}, {}
    if not requirements_text:
        print("[DEBUG] parse_requirements_hourly: empty input")
        return mins, ideals

    print(f"[DEBUG] parse_requirements_hourly: raw length={len(str(requirements_text))}")
    
    # Normalize separators and newlines
    text = requirements_text.replace('\r', '\n').replace(';', ',').strip()
    lines = [l for l in text.split('\n') if l.strip()]
    print(f"[DEBUG] Lines detected: {len(lines)}")
    
    # If everything is in one line, try to force split by "Team" keywords or patterns
    if len(lines) == 1:
        long_line = lines[0]
        # try to split at each "A,", "B,", "C,"...
        chunks = re.split(r'(?=[A-Z]\s*,)', long_line)
        lines = [l.strip() for l in chunks if l.strip()]
        print(f"[DEBUG] Split long line into {len(lines)} logical entries")

    for line in lines:
        parts = [p.strip() for p in line.split(',')]
        if len(parts) < 4:
            continue
        
        # Detect pattern like "Equipa A,09-10"
        if len(parts) >= 3 and ("Equipa" in parts[1] or "Team" in parts[1]):
            # Example: ['', 'Equipa A', '09-10', -1, 4, 3, 2...]
            team_code = parts[1].split()[-1].upper().strip()
            hour_range = parts[2]
            values = parts[3:]
            target = mins  # treat as minimums
        elif len(parts) >= 3 and re.match(r'^\d{2}-\d{2}$', parts[1]):
            # Example: ['Equipa A', '09-10', -1, 4, 3...]
            team_code = parts[0].split()[-1].upper().strip()
            hour_range = parts[1]
            values = parts[2:]
            target = mins
        else:
            # Fallback: normal ideal / min parsing
            team_label_raw, req_type, hour_range = parts[:3]
            values = parts[3:]
            team_match = re.search(r'([A-Za-z])$', team_label_raw)
            if not team_match:
                print(f"[DEBUG] Skipping invalid team_label: {team_label_raw}")
                continue
            team_code = team_match.group(1).upper()
            target = mins if 'min' in req_type.lower() else ideals

        for day_idx, val in enumerate(values, start=1):
            if val.isdigit():
                target[(day_idx, hour_range, team_code)] = int(val)
    
    print(f"[CHECK] Total mins={len(mins)} ideals={len(ideals)}")
    print(f"[CHECK] Sample mins: {list(mins.keys())[:10]}")

    print(f"[DEBUG] Created {len(mins)} mins and {len(ideals)} ideals")
    return mins, ideals

# ----------------------------------------------------------------------
def parse_employees(employees_json):
    teams = {}
    if not employees_json:
        return teams
    if isinstance(employees_json, str):
        try:
            employees_list = json.loads(employees_json)
        except Exception:
            employees_list = []
    else:
        employees_list = employees_json

    for emp in employees_list:
        name = emp.get("name", "")
        m = re.search(r'(\d+)', str(name))
        emp_id = int(m.group(1)) if m else emp.get("id", None)
        if emp_id is None:
            continue
        codes = []
        for t in emp.get("teams", []):
            mt = re.search(r'([A-Za-z])\s*$', str(t))
            if mt:
                codes.append(mt.group(1).upper())
        seen = set()
        codes = [c for c in codes if not (c in seen or seen.add(c))]
        teams[int(emp_id)] = codes
    return teams


# ----------------------------------------------------------------------
# LOCAL TESTING MAIN
# ----------------------------------------------------------------------
if __name__ == "__main__":
    print("="*80)
    print("LOCAL TESTING MODE - kpiVerification_HoursLocal.py")
    print("="*80)
    
    # Configuration for local testing
    CSV_FILE = "Horário_Por_Intervalos_1Hora.csv"
    
    # Sample holidays (customize as needed)
    holidays_list = [
        date(2021, 12, 25),  # Christmas
        date(2022, 1, 1),    # New Year
        date(2022, 4, 15),   # Good Friday (example)
    ]
    
    # Sample minimums requirements (customize as needed)
    # Format: "Team Label,Type,Hour Range,Day1,Day2,...Day365"
    minimums_text = """
Team A,min,09-10,-1,4,4,4,4,4,4,-1,4,4,4,4,4,4,-1,4,4,4,4,4,4,-1,4,4,4,4,4,4,-1
Team A,min,10-11,-1,3,3,3,3,3,3,-1,3,3,3,3,3,3,-1,3,3,3,3,3,3,-1,3,3,3,3,3,3,-1
Team B,min,09-10,-1,2,2,2,2,2,2,-1,2,2,2,2,2,2,-1,2,2,2,2,2,2,-1,2,2,2,2,2,2,-1
"""
    
    # Sample employees (customize as needed)
    employees_data = [
        {"name": "Employee 1", "teams": ["Team A"]},
        {"name": "Employee 2", "teams": ["Team A", "Team B"]},
        {"name": "Employee 3", "teams": ["Team B"]},
    ]
    
    print(f"\nReading CSV: {CSV_FILE}")
    print(f"Holidays: {len(holidays_list)} defined")
    print(f"Employees: {len(employees_data)} defined")
    print("\n" + "="*80)
    
    try:
        # Call analyze function
        kpi_results = analyze(
            file=CSV_FILE,
            holidays=holidays_list,
            mins=minimums_text,
            employees=employees_data,
            year=2022
        )
        
        print("\n" + "="*80)
        print("KPI RESULTS")
        print("="*80)
        for key, value in kpi_results.items():
            print(f"{key:30s}: {value}")
        print("="*80)
        
    except FileNotFoundError:
        print(f"\n[ERROR] CSV file not found: {CSV_FILE}")
        print("Please ensure the CSV file exists in the same directory as this script.")
    except Exception as e:
        print(f"\n[ERROR] Exception occurred: {e}")
        traceback.print_exc()